# Config for https://github.com/toolmantim/release-drafter
name-template: 'Akka gRPC $NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: 'Client side'
    label: 'client'
  - title: 'Server side'
    label: 'server'
  - title: 'Internal changes'
    label: 'development'
  - title: 'Gradle'
    label: 'gradle'
  - title: 'Maven'
    label: 'maven'
  - title: 'sbt'
    label: 'sbt'
  - title: 'Updates'
    label: 'update'

change-template: '- $TITLE [#$NUMBER](https://github.com/akka/akka-grpc/issues/$NUMBER) by [@$AUTHOR](https://github.com/$AUTHOR)'
template: |
  ## Changes

  $CHANGES
