version: 3
# https://github.com/fossas/fossa-cli/blob/master/docs/references/files/fossa-yml.md

targets:
  # exclude non-distributed projects from dependency scanning
  exclude:
    - type: scala
      path: benchmarks
    - type: scala
      path: interop-tests
    - type: scala
      path: plugin-tester-java
    - type: scala
      path: plugin-tester-scala
