// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package io.akka.grpc.helloworld

object HelloworldProto extends _root_.com.trueaccord.scalapb.GeneratedFileObject {
  lazy val dependencies: Seq[_root_.com.trueaccord.scalapb.GeneratedFileObject] = Seq()
  lazy val messagesCompanions: Seq[_root_.com.trueaccord.scalapb.GeneratedMessageCompanion[_]] = Seq(
    io.akka.grpc.helloworld.HelloRequest,
    io.akka.grpc.helloworld.HelloReply)
  private lazy val ProtoBytes: Array[Byte] =
    com.trueaccord.scalapb.Encoding.fromBase64(scala.collection.Seq(
      """ChBoZWxsb3dvcmxkLnByb3RvEgpoZWxsb3dvcmxkIiIKDEhlbGxvUmVxdWVzdBISCgRuYW1lGAEgASgJUgRuYW1lIiYKCkhlb
  GxvUmVwbHkSGAoHbWVzc2FnZRgBIAEoCVIHbWVzc2FnZTLXAQoHR3JlZXRlchI+CghTYXlIZWxsbxIYLmhlbGxvd29ybGQuSGVsb
  G9SZXF1ZXN0GhYuaGVsbG93b3JsZC5IZWxsb1JlcGx5IgASRgoOSXRLZWVwc1RhbGtpbmcSGC5oZWxsb3dvcmxkLkhlbGxvUmVxd
  WVzdBoWLmhlbGxvd29ybGQuSGVsbG9SZXBseSIAKAESRAoMU3RyZWFtSGVsbG9zEhguaGVsbG93b3JsZC5IZWxsb1JlcXVlc3QaF
  i5oZWxsb3dvcmxkLkhlbGxvUmVwbHkiACgBQiEKDGlvLmFra2EuZ3JwY0IPSGVsbG9Xb3JsZFByb3RvUAFiBnByb3RvMw==""").mkString)
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = com.google.protobuf.descriptor.FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom(scalaProto, dependencies.map(_.scalaDescriptor))
  }
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val javaProto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(ProtoBytes)
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(javaProto, Array())
  }
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}