package com.lightbend.grpc.interop

import scala.concurrent.Future

import akka.http.scaladsl.model.{ HttpRequest, HttpResponse, StatusCodes }

import akka.http.grpc.Grpc

import org.scalatest.WordSpec

// Generated by our plugin
import io.grpc.testing.integration.test.TestServiceServiceHandler

class GrpcInteropSpec extends WordSpec with GrpcInteropTests {
  override val pendingAkkaTestCases = Seq(
    "ping_pong",
    "server_streaming",
    "cancel_after_first_response",
    "custom_metadata",
    "unimplemented_method",
    "status_code_and_message",
    "client_compressed_unary",
    "client_compressed_streaming",
    "server_compressed_streaming",
  )

  akkaHttpGrpcTests(implicit mat => implicit ec => TestServiceServiceHandler(new TestServiceImpl()))
}
