name: Link Validator

on:
  workflow_dispatch:
  pull_request:
  schedule:
    - cron:  '0 6 1 * *'

permissions:
  contents: read

jobs:
  validate-links:
    runs-on: Akka-Default
    steps:
      - name: Checkout
        # https://github.com/actions/checkout/releases
        uses: actions/checkout@v6
        with:
          # fetch everything https://github.com/actions/checkout#fetch-all-history-for-all-tags-and-branches
          fetch-depth: 0

      - name: Setup global resolver
        uses: ./.github/actions/global-resolver

      - name: Cache Coursier cache
        # https://github.com/coursier/cache-action/releases
        uses: coursier/cache-action@v8.1.0

      - name: Set up JDK 25
        # https://github.com/coursier/setup-action/releases
        uses: coursier/setup-action@v3.0.0
        with:
          jvm: temurin:1.25
          apps: cs

      - name: sbt site
        run: |
          cp .jvmopts-ghactions .jvmopts
          sbt akka-grpc-docs/makeSite

      - name: Run Link Validator
        run: |
          VERSION=$(ls docs/target/site/libraries/akka-grpc)
          sed -e "s/snapshot/$VERSION/" scripts/link-validator.conf > /tmp/link-validator.conf
          cs launch net.runne::site-link-validator:0.2.5 -- /tmp/link-validator.conf
