name: Link Validator

on:
  workflow_dispatch:
  pull_request:
  schedule:
    - cron:  '0 6 1 * *'

permissions:
  contents: read

jobs:
  validate-links:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        # https://github.com/actions/checkout/releases
        # v4.1.1
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        with:
          # fetch everything https://github.com/actions/checkout#fetch-all-history-for-all-tags-and-branches
          fetch-depth: 0

      - name: Cache Coursier cache
        # https://github.com/coursier/cache-action/releases
        # v6.4.5
        uses: coursier/cache-action@1ff273bff02a8787bc9f1877d347948af647956d

      - name: Set up JDK 17
        # https://github.com/coursier/setup-action/releases
        # v1.3.5
        uses: coursier/setup-action@7bde40eee928896f074dbb76d22dd772eed5c65f
        with:
          jvm: temurin:1.17
          apps: cs

      - name: sbt site
        run: |
          cp .jvmopts-ghactions .jvmopts
          sbt akka-grpc-docs/makeSite

      - name: Run Link Validator
        run: |
          VERSION=$(ls docs/target/site/libraries/akka-grpc)
          sed -e "s/snapshot/$VERSION/" scripts/link-validator.conf > /tmp/link-validator.conf
          cs launch net.runne::site-link-validator:0.2.5 -- /tmp/link-validator.conf
