name: PR Labeler
on:
  pull_request:
    types: [opened]

jobs:
  pr-labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      # https://github.com/TimonVS/pr-labeler-action/releases
      # v4.1.1
      - uses: TimonVS/pr-labeler-action@8b99f404a073744885d8021d1de4e40c6eaf38e2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
